//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Vaccination = new HashSet<Vaccination>();
        }
    
        public int NumCustomer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Id { get; set; }
        public int AddressId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public int VaccinationId { get; set; }
        public string img { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> Cuvid19Positive { get; set; }
        public Nullable<System.DateTime> Recovery { get; set; }
        
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination> Vaccination { get; set; }
    }
}
